### ISSUE TITLE
ModuleNotFoundError: No module named 'ratelim'

### ISSUE THREAD

**Issue by grekichi** [DenisCarriere/geocoder#460] opened 2023-06-23 10:02 UTC
Hi there !
I tried to use geocoder.google(~, method='reverse').
It happened this error. for detail below,
~ geocoder/freegeoip.py", line 8, in <module> ~
Should I install 'retelim' also for using geocoder ?

**Comment by vihaanmody1** [comment] 2023-07-26 20:00
If it tells you this, you should install 'retelim'. If it doesn't work, reinstall geocoder.

**Comment by grekichi** [comment] 2023-07-27 01:39
Thanks for communication, Vihaan.

I tried install retelim and the other modules.
But 'geocoder.google' could not run.
Isn't it need to register google API ?

So I tried 'geocoder.osm', and it worked !

**Comment by vihaanmody1** [comment] 2023-07-29 22:09
Nice to hear that the problem is fixed. Please close this issue.

**Closed as completed** 2023-07-30 00:57 UTC
