### ISSUE TITLE
Google client keys don't get picked up

### ISSUE THREAD

**Issue by avanderm** [DenisCarriere/geocoder#279] opened 2017-08-23 14:01 UTC
We noticed that after upgrading geocoder from 1.25.0 to later versions, the Google environment variables when using a client account do not get picked up, here is the error:
```ValueError                                Traceback (most recent call last)
<ipython-input-3-4e48b1d75176> in <module>()
----> 1 geocoder.google(address)

.../geocoder/api.py in google(location, **kwargs)
    193         > elevation
    194     """
--> 195     return get(location, provider='google', **kwargs)
    196 
    197 

.../geocoder/api.py in get(location, **kwargs)
    159         if method not in options[provider]:
    160             raise ValueError("Invalid method")
--> 161     return options[provider][method](location, **kwargs)
    162 
    163 

.../geocoder/base.py in __init__(self, location, **kwargs)
    706 
    707         # check validity of provider key
--> 708         provider_key = self._get_api_key(kwargs.pop('key', None))
    709 
    710         # point to geocode, as a string or coordinates

.../geocoder/base.py in _get_api_key(cls, key)
    685         # raise exception if not valid key found
    686         if not key:
--> 687             raise ValueError('Provide API Key')
    688 
    689         return key

ValueError: Provide API Key

**Comment by avanderm** [comment] 2017-08-23 15:39
It searches for an API key in MultipleResultsQuery in base.py, thus throwing an error if only a client + secret is passed.

**Comment by DenisCarriere** [comment] 2017-08-23 15:39
uh.. 🤔 Good catch... not too sure what would of caused that.

@ebreton Any clue?

**Comment by DenisCarriere** [comment] 2017-08-23 15:48
@avanderm Feel free to push a PR with a fix, can't pinpoint exactly what's the cause at the moment.

**Comment by avanderm** [comment] 2017-08-23 16:05
Will look into it when I have time, this error seems to be causing a lot of the tests to fail

**Comment by ebreton** [comment] 2017-08-23 16:11
I will have a loot at it too.

What would be great though, when we have fixed this, would be to have the tests merged in the base code... we are lacking a few of them :)

**Comment by ebreton** [comment] 2017-08-23 16:19
Ok, I think I got it:

It breaks because I have made the "traditionnal api key" **mandatory** 👎 . 
And, correct me if I am wrong, but you do not need it when using google client / secret.

I will push a fix in a branch. @avanderm : will you be able to test from that branch and tell me if that fixes the issue. -> We will be able to merge and release a patch afterwards

**Comment by avanderm** [comment] 2017-08-23 16:42
Issue fixed for me, thank you very much!

**Comment by DenisCarriere** [comment] 2017-08-23 17:52
Perfect! 👍

**Closed** 2017-08-24 07:55 UTC
Labels: bug
